sudo: required
dist: trusty

language: cpp

cache:
  - apt
  - directories:
    - ThirdLibrary/Tools
    #- ThirdLibrary/src
    #- ThirdLibrary/unix
    #- ThirdLibrary/windows_mingw

compiler:
  - g++

jdk: oraclejdk7

#android:
#  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    #- platform-tools
    #- tools
#     - build-tools-18.1.1
#     - android-18
#     - extra

os:
  - linux
  #- android
  #- osx
  #- windows_mingw

env:
  matrix:
    - QT_VERSION_DIR=5.6 QT_VERSION=5.6.0 
    - QT_VERSION_DIR=5.5 QT_VERSION=5.5.1
    - QT_VERSION_DIR=5.4 QT_VERSION=5.4.2
    - QT_VERSION_DIR=5.3 QT_VERSION=5.3.2
    - QT_VERSION_DIR=5.2 QT_VERSION=5.2.1

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: 
  - bash ThirdLibrary/build_script/ci/build_${TRAVIS_OS_NAME}.sh `pwd`

notifications:
  email: kl222@126.com
  on_success: never  # [always|never|change]
  on_failure: always
