#TODO:版本变更时，修改成相应的版本
version: '0.1.1.{build}'

environment:
  matrix:
 
  ##### 测试 #####
  - BUILD_TARGET: windows_mingw
    toolchain_version: 530
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: change_prefix openssl libcurl libvpx libyuv x264 ffmpeg qrencode
  
  - BUILD_TARGET: windows_mingw
    toolchain_version: 492
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: change_prefix openssl libcurl libvpx libyuv x264 ffmpeg qrencode
    RABBITIM_USE_REPOSITORIES: "FALSE"

  - BUILD_TARGET: windows_mingw
    toolchain_version: 530
    QT_VERSION: qt5.7
    QT_ROOT: /C/Qt/5.7/mingw53_32
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: qxmpp qzxing 
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_mingw530_x86__v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"

  ##### 测试 #####
 
  ##### 基本库编译 #####
  - BUILD_TARGET: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    toolchain_version: 14
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: openssl libcurl libvpx libyuv x264 ffmpeg
    RABBITIM_USE_REPOSITORIES: "FALSE"
    
  - BUILD_TARGET: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    toolchain_version: 12
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: openssl libcurl libvpx libyuv x264 ffmpeg
  
  - BUILD_TARGET: windows_mingw
    toolchain_version: 530
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: change_prefix openssl libcurl libvpx libyuv x264 ffmpeg qrencode
    
  - BUILD_TARGET: windows_mingw
    toolchain_version: 492
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: change_prefix openssl libcurl libvpx libyuv x264 ffmpeg qrencode
    RABBITIM_USE_REPOSITORIES: "FALSE"
    
  - BUILD_TARGET: windows_mingw
    toolchain_version: 491
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: change_prefix openssl libcurl libvpx libyuv x264 ffmpeg qrencode
    RABBITIM_USE_REPOSITORIES: "FALSE"
    
  - BUILD_TARGET: windows_mingw
    toolchain_version: 482
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: change_prefix openssl libcurl libvpx libyuv x264 ffmpeg qrencode
    RABBITIM_USE_REPOSITORIES: "FALSE"
    
  ##### 基本库编译 #####
  
  ##### QT相关编译 #####
  - BUILD_TARGET: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    toolchain_version: 14
    QT_VERSION: qt5.7
    QT_ROOT: /C/Qt/5.7/msvc2015
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: qxmpp qzxing 
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_msvc14_x86__v$(appveyor_build_version).zip/download
  
  - BUILD_TARGET: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    toolchain_version: 14
    QT_VERSION: qt5.6.1
    QT_ROOT: /C/Qt/5.6/msvc2015
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: qxmpp qzxing 
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_msvc14_x86__v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"
    
  - BUILD_TARGET: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    toolchain_version: 12
    QT_VERSION: qt5.7
    QT_ROOT: /C/Qt/5.7/msvc2013
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: qxmpp qzxing 
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_msvc12_x86__v$(appveyor_build_version).zip/download

  - BUILD_TARGET: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    toolchain_version: 12
    QT_VERSION: qt5.6.1
    QT_ROOT: /C/Qt/5.6/msvc2013
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: qxmpp qzxing 
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_msvc12_x86__v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"
    
  - BUILD_TARGET: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    toolchain_version: 12
    QT_VERSION: qt5.5
    QT_ROOT: /C/Qt/5.5/msvc2013
    AUTOBUILD_ARCH: x86  
    RABBITIM_BUILD_THIRDLIBRARY: qxmpp qzxing 
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_msvc12_x86__v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"
    
  - BUILD_TARGET: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    toolchain_version: 12
    QT_VERSION: qt5.4
    QT_ROOT: /C/Qt/5.4/msvc2013_opengl
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: qxmpp qzxing 
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_msvc12_x86__v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"
   
  - BUILD_TARGET: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    toolchain_version: 12
    QT_VERSION: qt5.3
    QT_ROOT: /C/Qt/5.3/msvc2013_opengl
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: qxmpp qzxing 
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_msvc12_x86__v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"
    
  - BUILD_TARGET: windows_mingw
    toolchain_version: 530
    QT_VERSION: qt5.7
    QT_ROOT: /C/Qt/5.7/mingw53_32
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: qxmpp qzxing 
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_mingw530_x86__v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"
    
  - BUILD_TARGET: windows_mingw
    toolchain_version: 492
    QT_VERSION: qt5.6
    QT_ROOT: /C/Qt/5.6/mingw49_32
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: qxmpp qzxing 
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_mingw492_x86__v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"
    
  - BUILD_TARGET: windows_mingw
    toolchain_version: 492
    QT_VERSION: qt5.5
    QT_ROOT: /C/Qt/5.5/mingw492_32
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: qxmpp qzxing 
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_mingw492_x86__v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"
    
  - BUILD_TARGET: windows_mingw
    toolchain_version: 491
    QT_VERSION: qt5.4
    QT_ROOT: /C/Qt/5.4/mingw491_32
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: qxmpp qzxing 
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_mingw491_x86__v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"

  - BUILD_TARGET: windows_mingw
    toolchain_version: 482
    QT_VERSION: qt5.3
    QT_ROOT: /C/Qt/5.3/mingw482_32
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: qxmpp qzxing 
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_mingw482_x86__v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"
  ##### QT相关编译 #####

  ##### rabbitim #####
  - BUILD_TARGET: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    toolchain_version: 14
    QT_VERSION: qt5.7
    QT_ROOT: /C/Qt/5.7/msvc2015
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: rabbitim
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_msvc14_x86_qt5.7_v$(appveyor_build_version).zip/download
  
  - BUILD_TARGET: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    toolchain_version: 14
    QT_VERSION: qt5.6.1
    QT_ROOT: /C/Qt/5.6/msvc2015
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: rabbitim
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_msvc14_x86_qt5.6.1_v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"
    
  - BUILD_TARGET: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    toolchain_version: 12
    QT_VERSION: qt5.7
    QT_ROOT: /C/Qt/5.7/msvc2013
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: rabbitim 
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_msvc12_x86_qt5.7_v$(appveyor_build_version).zip/download

  - BUILD_TARGET: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    toolchain_version: 12
    QT_VERSION: qt5.6.1
    QT_ROOT: /C/Qt/5.6/msvc2013
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: rabbitim
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_msvc12_x86_qt5.6.1_v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"
    
  - BUILD_TARGET: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    toolchain_version: 12
    QT_VERSION: qt5.5
    QT_ROOT: /C/Qt/5.5/msvc2013
    AUTOBUILD_ARCH: x86  
    RABBITIM_BUILD_THIRDLIBRARY: rabbitim 
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_msvc12_x86_qt5.5_v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"
    
  - BUILD_TARGET: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    toolchain_version: 12
    QT_VERSION: qt5.4
    QT_ROOT: /C/Qt/5.4/msvc2013_opengl
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: rabbitim 
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_msvc12_x86_qt5.4_v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"
   
  - BUILD_TARGET: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    toolchain_version: 12
    QT_VERSION: qt5.3
    QT_ROOT: /C/Qt/5.3/msvc2013_opengl
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: rabbitim
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_msvc12_x86_qt5.3_v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"
    
  - BUILD_TARGET: windows_mingw
    toolchain_version: 530
    QT_VERSION: qt5.7
    QT_ROOT: /C/Qt/5.7/mingw53_32
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: rabbitim 
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_mingw530_x86_qt5.7_v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"
    
  - BUILD_TARGET: windows_mingw
    toolchain_version: 492
    QT_VERSION: qt5.6
    QT_ROOT: /C/Qt/5.6/mingw49_32
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: rabbitim
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_mingw492_x86_qt5.6_v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"
    
  - BUILD_TARGET: windows_mingw
    toolchain_version: 492
    QT_VERSION: qt5.5
    QT_ROOT: /C/Qt/5.5/mingw492_32
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: rabbitim
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_mingw492_x86_qt5.5_v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"
    
  - BUILD_TARGET: windows_mingw
    toolchain_version: 491
    QT_VERSION: qt5.4
    QT_ROOT: /C/Qt/5.4/mingw491_32
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: rabbitim
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_mingw491_x86_qt5.4_v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"

  - BUILD_TARGET: windows_mingw
    toolchain_version: 482
    QT_VERSION: qt5.3
    QT_ROOT: /C/Qt/5.3/mingw482_32
    AUTOBUILD_ARCH: x86
    RABBITIM_BUILD_THIRDLIBRARY: rabbitim
    DOWNLOAD_FILE: https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_windows_mingw482_x86_qt5.3_v$(appveyor_build_version).zip/download
    RABBITIM_USE_REPOSITORIES: "FALSE"
  ##### rabbitim #####
  
matrix:
  fast_finish: false

init:
  - set varch=%AUTOBUILD_ARCH%
  - if "%AUTOBUILD_ARCH%" == "x64" set varch=amd64
  - if "%BUILD_TARGET%"=="windows_msvc" call "C:\Program Files (x86)\Microsoft Visual Studio %toolchain_version%.0\VC\vcvarsall.bat" %varch%
  #- if "%BUILD_TARGET%"=="windows_mingw" set PATH=C:\Qt\Tools\mingw%toolchain_version%_32\bin;%PATH%
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
  - echo QT_ROOT=%QT_ROOT%
  - del C:\msys64\usr\bin\link.exe

install:
  #- C:\msys64\usr\bin\pacman.exe -Syu --noconfirm 
  #- C:\msys64\autorebase.bat
  - C:\msys64\usr\bin\pacman.exe -S --noconfirm nasm yasm unzip curl
  - C:\msys64\autorebase.bat

#before_build:
  #- ps: foreach($artifactName in $artifacts.keys) { Write-Host  $artifacts[$artifactName] }
  #- cd ThirdLibrary
  #- if not "%FLAG%"=="start" wget -O RabbitIm_%BUILD_TARGET%_v%APPVEYOR_BUILD_VERSION%.zip https://sourceforge.net/projects/rabbitim-third-library/files/release/ThirdLibrary/RabbitIm_%BUILD_TARGET%_v%APPVEYOR_BUILD_VERSION%.zip/download || set ERRORLEVEL=0 && echo "download fail"
  #- if not "%FLAG%"=="start" wget -O RabbitIm_%BUILD_TARGET%_v%APPVEYOR_BUILD_VERSION%.zip https://ci.appveyor.com/api/projects/kanglin/rabbitim/ThirdLibrary/RabbitIm_%BUILD_TARGET%_v%APPVEYOR_BUILD_VERSION%.zip?job=RABBITIM_BUILD_THIRDLIBRARY%3dlibvpx%2c+BUILD_TARGET%3dwindows_msvc%2c+AUTOBUILD_ARCH%3dx86%2c+AUTOBUILD_COMPLER%3dVS2013%2c+toolchain_version%3d12%2c+mode%3drelease%2c+FLAG%3dstart
  #- dir 
  #- if EXIST RabbitIm_%BUILD_TARGET%_v%APPVEYOR_BUILD_VERSION%.zip unzip RabbitIm_%BUILD_TARGET%_v%APPVEYOR_BUILD_VERSION%.zip -d %BUILD_TARGET%
  #- dir 

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\ThirdLibrary\build_script\ci\build_windows.sh

#after_build:

artifacts:
 # - path: ThirdLibrary/src
 #   name: RabbitImThirdLibrarySource
    
  - path: ThirdLibrary/$(BUILD_TARGET)
    name: RabbitIm_$(BUILD_TARGET)$(toolchain_version)_$(AUTOBUILD_ARCH)_$(QT_VERSION)_v$(appveyor_build_version)
    type: zip
    
  - path: build_$(BUILD_TARGET)/install
    name: RabbitIm_$(BUILD_TARGET)$(toolchain_version)_$(AUTOBUILD_ARCH)_$(QT_VERSION)_v$(appveyor_build_version)
    type: zip

test: off

deploy:
  provider: FTP 
  protocol: sftp 
  host: frs.sourceforge.net 
  username: kl222,rabbitim-third-library
  #密码用这个加密 https://ci.appveyor.com/tools/encrypt
  password: 
    secure: 2WEtOQrdty3V3g0aEVvS3Q== 
  folder: pfs/project/rabbitim-third-library/release
  draft: false
  active_mode: false 

#deploy:
#  provider: GitHub
#  release: rabbitim-third-library-v$(appveyor_build_version)
#  description: 'rabbitim-third-library-v$(appveyor_build_version)'
#  #token 在这个地址产生 https://github.com/settings/tokens 用这个加密 https://ci.appveyor.com/tools/encrypt
#  auth_token:
#    secure: ZwS9M6Ide+GfM4kLxJ5b9tRoB1wn/56nZRCAIP6Z7s3+YwcE+cx0Dv0d6X82lidF
#  draft: false
#  prerelease: false
#  on:
#    branch: master                 # release from master branch only
#    #appveyor_repo_tag: true        # deploy on tag push only
