#TODO:版本变更时，修改成相应的版本
version: '0.1.1.{build}'

environment:
  matrix:
  ##### msvc 2017 ########
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILD_TARGERT: windows_msvc
    RABBIT_TOOLCHAIN_VERSION: 15
    RABBIT_ARCH: x64
    RABBIT_CONFIG: Release
    QT_VERSION: 5.9.2
    QT_ROOT: /C/Qt/5.9/msvc2017_64
  
matrix:
  fast_finish: false

init:
  - set RABBITIM_LIBRARY=qxmpp qzxing rabbitim
  - set varch=%RABBIT_ARCH%
  - set PROJECT_NAME=%APPVEYOR_PROJECT_NAME%
  - if %QT_VERSION% == "" set QT_VERSION=NO
  - if "%RABBIT_ARCH%" == "x64" set varch=amd64
  - if "%BUILD_TARGERT%" == "windows_msvc" if %RABBIT_TOOLCHAIN_VERSION% LSS 15 (call "C:\Program Files (x86)\Microsoft Visual Studio %RABBIT_TOOLCHAIN_VERSION%.0\VC\vcvarsall.bat" %varch%) else (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %varch%)
  - if "%BUILD_TARGERT%" == "windows_mingw" set MSYSTEM=MINGW32  #设置编译系统为MINGW32
  #- if NOT "%QT_ROOT%" == "NO" for /f "delims=" %%i in ('%QT_ROOT%/bin/qmake -query QT_VERSION') do (set QT_VERSION=%%i)
  - echo QT_VERSION=%QT_VERSION%
  - echo QT_ROOT=%QT_ROOT%
  - del C:\msys64\usr\bin\link.exe
  
install:
  - for /f "delims=" %%i in ('git describe --tags') do (set BUILD_VERSION=%%i)
  - if "%BUILD_VERSION%" == "" for /f "delims=" %%i in ('git rev-parse HEAD') do (set BUILD_VERSION=%%i) 
  - echo BUILD_VERSION=%BUILD_VERSION%
  - if not "%BUILD_TARGERT%" == "android" C:\msys64\usr\bin\pacman.exe -S --noconfirm nasm yasm 
  - C:\msys64\usr\bin\pacman.exe -S --noconfirm unzip expect #zip curl
  - C:\msys64\autorebase.bat
  - set DOWNLOAD_URL=https://github.com/KangLin/RabbitThirdLibrary/releases/download/v0.0.2/RABBIT_%BUILD_TARGERT%%RABBIT_TOOLCHAIN_VERSION%_%RABBIT_ARCH%_qtNO_%RABBIT_CONFIG%_v0.0.2.zip
  - set RABBIT_BUILD_PREFIX=%APPVEYOR_BUILD_FOLDER%/ThirdLibrary/%BUILD_TARGERT%
  
before_build:
  - git submodule update --init --recursive
  - cd %APPVEYOR_BUILD_FOLDER%
  - if "%BUILD_TARGERT%" == "android" C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\ThirdLibrary\build_script\ci\build-install-tools-windows.sh

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\ThirdLibrary\build_script\ci\build.sh
  - if "%BUILD_TARGERT%" == "windows_msvc" copy "%APPVEYOR_BUILD_FOLDER%\Install\Install.nsi" "%APPVEYOR_BUILD_FOLDER%\build_%BUILD_TARGERT%"  && cd "%APPVEYOR_BUILD_FOLDER%\build_%BUILD_TARGERT%" && "C:\Program Files (x86)\NSIS\makensis.exe" "Install.nsi"

#after_build:

artifacts:
  - path: build_${BUILD_TARGERT}/RabbitIM-Setup-*.exe
    name: RabbitIM_$(BUILD_TARGERT)$(RABBIT_TOOLCHAIN_VERSION)_$(RABBIT_ARCH)_qt$(QT_VERSION)_$(RABBIT_CONFIG)_$(BUILD_VERSION)
    type: zip

test: off

deploy:
  #provider: FTP 
  #protocol: sftp 
  #host: frs.sourceforge.net 
  #username: kl222,rabbitim
  #密码用这个加密 https://ci.appveyor.com/tools/encrypt
  #password:
  #  secure: 2WEtOQrdty3V3g0aEVvS3Q==
  #folder: pfs  #link pfs to /home/frs/project/r/ra/rabbitim
  #draft: false
  #active_mode: false
  #on:
    #branch: master

  - provider: GitHub
    #token : https://github.com/settings/tokens password encrypt: https://ci.appveyor.com/tools/encrypt
    auth_token:
      secure: xgIFN2iAfgj1gsWabdHrmFXvj0rce/ZWtKUwm3aDUNfLGu+kO/q94MYD8a46AbDL
    #artifact: RabbitGIS_$(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(AUTOBUILD_ARCH)_$(QT_VERSION)_v$(appveyor_build_version)
    #draft: true
    #prerelease: true
    on:
      BUILD_TARGERT: windows_msvc
      TOOLCHAIN_VERSION: 14
      QT_VERSION: qt5.7.1
      AUTOBUILD_ARCH: x86
      appveyor_repo_tag: true        # deploy on tag push only
